# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_in_english', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=120)),
                ('staff_type', models.CharField(choices=[('CH', 'Centre Head'), ('CS', 'CSS'), ('PS', 'Psychologist'), ('BA', 'Benefits advisor'), ('FR', 'Fundraiser'), ('SS', 'Sessional Staff')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TempVisitNameMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('UM', 'Under 18 Male'), ('UF', 'Under 18 Female')], max_length=2)),
                ('journey_stage', models.CharField(choices=[('PW', 'PwC'), ('CA', 'Carer'), ('PR', 'Professional'), ('AR', 'Architectural'), ('IN', 'International'), ('OV', 'Other visitor')], max_length=2)),
                ('nature_of_visit', models.CharField(choices=[('BO', 'Booked'), ('DI', 'Drop - In'), ('PR', 'Programme'), ('EM', 'E-mail support'), ('FR', 'Fundraising'), ('OR', 'Outreach'), ('TP', 'Telephone support')], max_length=2)),
                ('cancer_site', models.CharField(choices=[('BO', 'Booked'), ('DI', 'Drop - In'), ('PR', 'Programme'), ('EM', 'E-mail support'), ('FR', 'Fundraising'), ('OR', 'Outreach'), ('TP', 'Telephone support')], max_length=2)),
                ('type', models.CharField(choices=[('NE', 'New'), ('RE', 'Returning')], max_length=2)),
                ('activities', models.ManyToManyField(to='maggies_webapp.Activity')),
                ('seen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maggies_webapp.StaffMember')),
                ('visit_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggies_webapp.Centre')),
            ],
        ),
        migrations.AddField(
            model_name='tempvisitnamemapping',
            name='related_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggies_webapp.Visit'),
        ),
        migrations.AddField(
            model_name='centre',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maggies_webapp.Language'),
        ),
        migrations.AddField(
            model_name='activityname',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggies_webapp.Language'),
        ),
        migrations.AddField(
            model_name='activity',
            name='instructed_by',
            field=models.ManyToManyField(to='maggies_webapp.StaffMember'),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maggies_webapp.ActivityName'),
        ),
    ]
