# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maggies_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='scheduled_times_json',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='cancer_site',
            field=models.CharField(choices=[('BR', 'Brain / CNS'), ('GY', 'Gynae'), ('HN', 'Head / Neck'), ('HA', 'Haemat'), ('LI', 'Liver'), ('LO', 'Lower GI'), ('LU', 'Lung'), ('PA', 'Pancreatic'), ('PR', 'Prostate'), ('RA', 'Rare'), ('SA', 'Sarcoma'), ('SK', 'Skin / Mel'), ('TE', 'Testicular'), ('UK', 'Unknown Primary'), ('UG', 'Upper GI'), ('UR', 'Urolog'), ('NS', 'Not stated')], max_length=2),
        ),
    ]
