# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maggies_webapp', '0002_auto_20161105_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='centre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maggies_webapp.Centre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user_mapping',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
