# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maggies_webapp', '0003_auto_20161105_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AddField(
            model_name='activityname',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maggies_webapp.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maggies_webapp.Centre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='activities',
            field=models.ManyToManyField(blank=True, to='maggies_webapp.Activity'),
        ),
    ]
