# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maggies_webapp', '0004_auto_20161106_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempvisitnamemapping',
            name='isInBuilding',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='centre',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='centre',
            field=models.ManyToManyField(to='maggies_webapp.Centre'),
        ),
    ]
