# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maggies_webapp', '0007_auto_20161106_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 7, 29, 41, 827142, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='staff_type',
            field=models.CharField(choices=[('AD', 'Administrator'), ('CH', 'Centre Head'), ('CS', 'CSS'), ('PS', 'Psychologist'), ('BA', 'Benefits advisor'), ('FR', 'Fundraiser'), ('SS', 'Sessional Staff')], max_length=2),
        ),
    ]
